version: "3.7"
services:
    katalogize-api:
      container_name: katalogize-api
      restart: always
      build: ./
      ports:
        - "8080:8080"
      links:
        - mongo-db
    mongo-db:
      container_name: mongo
      restart: always
      image: mongo
      volumes:
        - ./data:/data/db
      ports:
        - '27017:27017'